# Generated by Django 3.1 on 2020-08-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanttosee',
            name='message',
            field=models.TextField(verbose_name='What would you like to see on Daniel Curtis?'),
        ),
    ]
